FROM ubuntu

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    curl \
    dnsutils \
    git \
    zsh \
    build-essential \
    hping3 \
    lsof \
    htop \
    apache2-utils \
    iputils-ping \
    iproute2 \
    nano \
    net-tools \
    libfcgi0ldbl \
    netcat-traditional \
    mtr \
    telnet \
    vim \
    wget \
    whois
